/**
 * 将小程序 utils/data 打包为浏览器预览脚本
 */
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const order = [
  '../data/bagua',
  '../data/guaci',
  './gua64-baihua',
  './gua64-xiaoxiang',
  './gua64-mojia',
  './gua64-xiangjie',
  './learning-boost',
  './learning-extra',
  '../data/learning',
  './ganzhi',
  './jixiang',
  './rules',
  './coin',
  './paipan',
  './ask-taxonomy',
  './ask',
  './ask-options',
  './duangu',
  './meihua'
]

const fileOf = {
  '../data/bagua': 'data/bagua.js',
  '../data/guaci': 'data/guaci.js',
  './gua64-baihua': 'data/gua64-baihua.js',
  './gua64-xiaoxiang': 'data/gua64-xiaoxiang.js',
  './gua64-mojia': 'data/gua64-mojia.js',
  './gua64-xiangjie': 'data/gua64-xiangjie.js',
  './learning-boost': 'data/learning-boost.js',
  './learning-extra': 'data/learning-extra.js',
  '../data/learning': 'data/learning.js',
  './ganzhi': 'utils/ganzhi.js',
  './jixiang': 'utils/jixiang.js',
  './rules': 'utils/rules.js',
  './coin': 'utils/coin.js',
  './paipan': 'utils/paipan.js',
  './ask-taxonomy': 'utils/ask-taxonomy.js',
  './ask': 'utils/ask.js',
  './ask-options': 'utils/ask-options.js',
  './duangu': 'utils/duangu.js',
  './meihua': 'utils/meihua.js'
}

const aliases = {
  './bagua': '../data/bagua',
  './guaci': '../data/guaci'
}

const modules = {}
order.forEach((id) => {
  modules[id] = fs.readFileSync(path.join(root, fileOf[id]), 'utf8')
})

const engine = `/* auto-generated by preview/build.js — do not edit by hand */
window.LiuYao = {};
;(function(){
var __mods = {};
function __require(id){
  var resolved = (${JSON.stringify(aliases)})[id] || id;
  if(__mods[resolved]) return __mods[resolved].exports;
  throw new Error('module not ready '+id);
}
${order.map((id) => {
  const code = modules[id].replace(/require\\((['"])(.+?)\\1\\)/g, '__require($1$2$1)')
  return `
__mods[${JSON.stringify(id)}] = { exports: {} };
(function(module, exports, require){
${code}
})(__mods[${JSON.stringify(id)}], __mods[${JSON.stringify(id)}].exports, __require);
`
}).join('\n')}

var coin = __require('./coin');
var paipan = __require('./paipan');
var duangu = __require('./duangu');
var meihua = __require('./meihua');
var jixiang = __require('./jixiang');
var askOptions = __require('./ask-options');
var learning = __require('../data/learning');
var bagua = __require('../data/bagua');
var guaci = __require('../data/guaci');
var guadian = __require('./gua64-xiangjie');
window.LiuYao = {
  tossThreeCoins: coin.tossThreeCoins,
  manualYao: coin.manualYao,
  arrangeCast: paipan.arrangeCast,
  buildPaipanGuide: paipan.buildPaipanGuide,
  interpret: duangu.interpret,
  TOPIC_YONGSHEN: duangu.TOPIC_YONGSHEN,
  guessTopicKey: duangu.guessTopicKey,
  castByNumbers: meihua.castByNumbers,
  castByTime: meihua.castByTime,
  castByRandom: meihua.castByRandom,
  buildLuckyDirections: jixiang.buildLuckyDirections,
  luckyByGan: jixiang.luckyByGan,
  TIME_SCOPES: askOptions.TIME_SCOPES,
  listGroups: askOptions.listGroups,
  buildAskSelection: askOptions.buildAskSelection,
  ARTICLES: learning.ARTICLES,
  getArticle: learning.getArticle,
  groupByCategory: learning.groupByCategory,
  volumeAnchorId: learning.volumeAnchorId,
  CATEGORY_ORDER: learning.CATEGORY_ORDER,
  CATEGORY_META: learning.CATEGORY_META,
  normalizeArticle: learning.normalizeArticle,
  TRIGRAMS: bagua.TRIGRAMS,
  buildBaguaDisk: bagua.buildBaguaDisk,
  XIANTIAN_LAYOUT: bagua.XIANTIAN_LAYOUT,
  HOUTIAN_LAYOUT: bagua.HOUTIAN_LAYOUT,
  listGuaDian: guaci.listGuaDian,
  filterGuaDian: guaci.filterGuaDian,
  PALACE_CHIP_ORDER: guaci.PALACE_CHIP_ORDER,
  buildPalaceCatalog: guadian.buildPalaceCatalog,
  getGuaXiangjie: guadian.getGuaXiangjie,
  GUA_STAGE: guadian.STAGE
};
})();
`

fs.writeFileSync(path.join(__dirname, 'engine.bundle.js'), engine)
console.log('wrote engine.bundle.js', engine.length)

const standalonePath = path.join(__dirname, 'liuyao-standalone.html')
const appPreview = fs.readFileSync(path.join(__dirname, 'app-preview.js'), 'utf8')
if (fs.existsSync(standalonePath)) {
  const html = fs.readFileSync(standalonePath, 'utf8')
  let n = 0
  const packed = html.replace(/<script>([\s\S]*?)<\/script>/g, () => {
    n += 1
    if (n === 1) return `<script>\n${engine}\n</script>`
    if (n === 2) return `<script>\n/* synced from app-preview.js by preview/build.js */\n${appPreview}\n</script>`
    return arguments[0]
  })
  if (n < 2) {
    throw new Error('liuyao-standalone.html expected two inline <script> tags, found ' + n)
  }
  fs.writeFileSync(standalonePath, packed)
  console.log('packed engine + app-preview into liuyao-standalone.html')
}
