/**
 * 将小程序 utils/data 打包为浏览器预览脚本
 */
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const order = [
  '../data/bagua',
  '../data/guaci',
  './learning-extra',
  '../data/learning',
  './ganzhi',
  './rules',
  './coin',
  './paipan',
  './ask-taxonomy',
  './ask',
  './ask-options',
  './duangu',
  './meihua'
]

const fileOf = {
  '../data/bagua': 'data/bagua.js',
  '../data/guaci': 'data/guaci.js',
  './learning-extra': 'data/learning-extra.js',
  '../data/learning': 'data/learning.js',
  './ganzhi': 'utils/ganzhi.js',
  './rules': 'utils/rules.js',
  './coin': 'utils/coin.js',
  './paipan': 'utils/paipan.js',
  './ask-taxonomy': 'utils/ask-taxonomy.js',
  './ask': 'utils/ask.js',
  './ask-options': 'utils/ask-options.js',
  './duangu': 'utils/duangu.js',
  './meihua': 'utils/meihua.js'
}

const modules = {}
order.forEach((id) => {
  modules[id] = fs.readFileSync(path.join(root, fileOf[id]), 'utf8')
})

const engine = `/* auto-generated by preview/build.js — do not edit by hand */
window.LiuYao = {};
;(function(){
var __mods = {};
function __require(id){
  if(__mods[id]) return __mods[id].exports;
  throw new Error('module not ready '+id);
}
${order.map((id) => {
  const code = modules[id].replace(/require\\((['"])(.+?)\\1\\)/g, '__require($1$2$1)')
  return `
__mods[${JSON.stringify(id)}] = { exports: {} };
(function(module, exports, require){
${code}
})(__mods[${JSON.stringify(id)}], __mods[${JSON.stringify(id)}].exports, __require);
`
}).join('\n')}

var coin = __require('./coin');
var paipan = __require('./paipan');
var duangu = __require('./duangu');
var meihua = __require('./meihua');
var askOptions = __require('./ask-options');
var learning = __require('../data/learning');
window.LiuYao = {
  tossThreeCoins: coin.tossThreeCoins,
  manualYao: coin.manualYao,
  arrangeCast: paipan.arrangeCast,
  buildPaipanGuide: paipan.buildPaipanGuide,
  interpret: duangu.interpret,
  TOPIC_YONGSHEN: duangu.TOPIC_YONGSHEN,
  guessTopicKey: duangu.guessTopicKey,
  castByNumbers: meihua.castByNumbers,
  castByTime: meihua.castByTime,
  castByRandom: meihua.castByRandom,
  TIME_SCOPES: askOptions.TIME_SCOPES,
  listGroups: askOptions.listGroups,
  buildAskSelection: askOptions.buildAskSelection,
  ARTICLES: learning.ARTICLES,
  getArticle: learning.getArticle,
  groupByCategory: learning.groupByCategory,
  CATEGORY_ORDER: learning.CATEGORY_ORDER,
  CATEGORY_META: learning.CATEGORY_META,
  normalizeArticle: learning.normalizeArticle
};
})();
`

fs.writeFileSync(path.join(__dirname, 'engine.bundle.js'), engine)
console.log('wrote engine.bundle.js', engine.length)
